In [2]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/99/2b/f7114983d84303019385d93d24d729aedba67be7e083286f114188943cf3/numpy-1.26.3-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 809.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 2.0 MB/s eta 0:00:08
   ---------------------------------------- 0.1/15.8 MB 1.8 MB/s eta 0:00:09
   ---------------------------------------- 0.2/15.8 MB 1.2 MB/s eta 0:00:13
    --------------------------------------- 0.2/15.8 MB 1.2 MB/s eta 0:00:13
    --------------------------------------- 0.2/15.8 MB 962.7 kB/s eta 0:00:17
    --------------------------------------- 0.3/15.8 MB 1.2 MB/s eta 0:00:14
    -------------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
rows=3
col=2
m=np.random.rand(rows,col)
print(m)

[[0.00622538 0.82488201]
 [0.22014709 0.16424176]
 [0.68798809 0.83807057]]


In [6]:
import numpy as np
# Creating two NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(array1)
print(array2)
# Addition
result_addition = array1 + array2
print("Addition Result:")
print(result_addition)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Addition Result:
[[ 6  8]
 [10 12]]


In [7]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(array1)
print(array2)
# Subtration
res_sub = array1 - array2
print("Subtraction Result")
print(res_sub)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Subtraction Result
[[-4 -4]
 [-4 -4]]


In [5]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(array1)
print(array2)
# Multiplication
res_mul = array1 * array2
print("Multiplication Result")
print(res_mul)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Multiplication Result
[[ 5 12]
 [21 32]]


In [6]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(array1)
print(array2)
#Division
res_div = array1 / array2
3
print("Division Result")
print(res_div)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Division Result
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
 import numpy as np
array1=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1)
print("first element of matrix:", array1[0,0])
print("Row 0:", array1[0, :])
print("Column 1:", array1[:, 1])
print("Subarray :", array1[0:2, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
first element of matrix: 1
Row 0: [1 2 3]
Column 1: [2 5 8]
Subarray : [[2 3]
 [5 6]]


In [9]:
import numpy as np
# Creating a 2D NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing to select specific rows and columns
# Selecting rows 1 to 2 and columns 1 to 3
sliced_array = my_array[0:2, 1:3]
# Printing the sliced array
print("Sliced Array (rows 1 to 2, columns 1 to 3):")
print(sliced_array)


Sliced Array (rows 1 to 2, columns 1 to 3):
[[2 3]
 [5 6]]


In [9]:
import numpy as np
array1=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
r_array=np.reshape(array1, (3,3))
print("Original array", array1)
4
print("Reshaped array", r_array)

Original array [1 2 3 4 5 6 7 8 9]
Reshaped array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np
import scipy
from scipy.integrate import quad
def my_function(x):
    return x**2
a=0
b=2
result,error=quad(my_function,a,b)
print("Numerical result: ",result)
print("estimated error: ",error)

Numerical result:  2.666666666666667
estimated error:  2.960594732333751e-14


In [11]:
import numpy as np
import scipy
from scipy.linalg import eig
matrix_size=2
B=np.random.rand(matrix_size, matrix_size)
eigenvalues,eigenvectors=eig(B)
print("Matrix B:")
print(B)
print("\nEigen Values:")
print(eigenvalues)
print("eigen Vectors:")
print(eigenvectors)

Matrix B:
[[0.57146109 0.08732557]
 [0.3676344  0.88361338]]

Eigen Values:
[0.48991643+0.j 0.96515804+0.j]
eigen Vectors:
[[-0.73088494 -0.21654611]
 [ 0.6825007  -0.97627239]]


In [13]:
import scipy

ModuleNotFoundError: No module named 'scipy'

In [10]:
import numpy as np
import scipy
from scipy.linalg import inv
matrix_size=2
c=np.random.rand(matrix_size,matrix_size)
c_inverse=inv(c)
print("Matrix C:")
print(c)
print("\n Inverse Matrix C:")
print(c_inverse)

ModuleNotFoundError: No module named 'scipy'

In [14]:
import pandas as pd
data={'Name': ['Alice','Bob','Charlie','David','Eve'],'Age': [28,22,30,26,24]}
df=pd.DataFrame(data)
age_summary=df['Age'].describe()
print(age_summary)


count     5.000000
mean     26.000000
std       3.162278
min      22.000000
25%      24.000000
50%      26.000000
75%      28.000000
max      30.000000
Name: Age, dtype: float64


In [14]:
import pandas as pd
data={'Name': ['Alice','Bob','Charlie','David','Eve'],'Age': [28,22,30,26,24]}
df=pd.DataFrame(data)
selected_columns=df[['Name','Age']]
filtered_df=selected_columns[selected_columns['Age']>25]
print(filtered_df)

      Name  Age
0    Alice   28
2  Charlie   30
3    David   26
